import type { Metadata } from "next";
import "@/global/assets/css/globals.css";
import { FloatingContactButtons, Footer, Navbar } from "@/global/components";

export const metadata: Metadata = {
  title: "Abogados Especialistas en Cobranza de Cartera | Grupo Coactiva SAS - Medellín, Bogotá, Cali",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/logos/logo.png", 
  },
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="es">
      <body>
        <main className="min-h-screen">
          <Navbar />
          {children}
          <FloatingContactButtons />
          <Footer />
        </main>
      </body>
    </html>
  );
}
